### ISSUE TITLE
Vorto repo unable to startup

### ISSUE THREAD

**Issue by vlvanchin** [eclipse/vorto#1191]
Steps to reproduce:

1. take the latest code from eclipse/vorto repo development branch
2. do a Maven clean install
3. Start the Spring Boot app for Vorto repo in repository/repository-server project folder

Actual Outcome:
- the repo server fails to startup 
- give the following stack trace

```
Error starting ApplicationContext. To display the auto-configuration report re-run your application with 'debug' enabled.
2018-11-27 06:28:20.333 ERROR 12 --- [           main] o.s.boot.SpringApplication               : Application startup failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'handlerExceptionResolver' defined in class path resource [org/springframework/boot/autoconfigure/web/WebMvcAutoConfiguration$EnableWebMvcConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.web.servlet.HandlerExceptionResolver]: Factory method 'handlerExceptionResolver' threw exception; nested exception is java.lang.IllegalStateException: Ambiguous @ExceptionHandler method mapped for [class org.eclipse.vorto.repository.core.ModelAlreadyExistsException]: {public void org.eclipse.vorto.repository.web.core.PayloadMappingController.modelExists(org.eclipse.vorto.repository.core.ModelAlreadyExistsException), public void org.eclipse.vorto.repository.web.AbstractRepositoryController.ModelExists(org.eclipse.vorto.repository.core.ModelAlreadyExistsException)}
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:599) ~[spring-beans-4.3.17.RELEASE.jar!/:4.3.17.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1181) ~[spring-beans-4.3.17.RELEASE.jar!/:4.3.17.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1075) ~[spring-beans-4.3.17.RELEASE.jar!/:4.3.17.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:513) ~[spring-beans-4.3.17.RELEASE.jar!/:4.3.17.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483) ~[spring-beans-4.3.17.RELEASE.jar!/:4.3.17.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:312) ~[spring-beans-4.3.17.RELEASE.jar!/:4.3.17.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.3.17.RELEASE.jar!/:4.3.17.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:308) ~[spring-beans-4.3.17.RELEASE.jar!/:4.3.17.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) ~[spring-beans-4.3.17.RELEASE.jar!/:4.3.17.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:761) ~[spring-beans-4.3.17.RELEASE.jar!/:4.3.17.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:867) ~[spring-context-4.3.17.RELEASE.jar!/:4.3.17.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:543) ~[spring-context-4.3.17.RELEASE.jar!/:4.3.17.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122) ~[spring-boot-1.5.13.RELEASE.jar!/:1.5.13.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693) [spring-boot-1.5.13.RELEASE.jar!/:1.5.13.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360) [spring-boot-1.5.13.RELEASE.jar!/:1.5.13.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303) [spring-boot-1.5.13.RELEASE.jar!/:1.5.13.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118) [spring-boot-1.5.13.RELEASE.jar!/:1.5.13.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107) [spring-boot-1.5.13.RELEASE.jar!/:1.5.13.RELEASE]
	at org.eclipse.vorto.repository.web.VortoRepository.main(VortoRepository.java:33) [classes!/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_111]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_111]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_111]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_111]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [infomodelrepository.jar:na]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [infomodelrepository.jar:na]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [infomodelrepository.jar:na]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51) [infomodelrepository.jar:na]
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.web.servlet.HandlerExceptionResolver]: Factory method 'handlerExceptionResolver' threw exception; nested exception is java.lang.IllegalStateException: Ambiguous @ExceptionHandler method mapped for [class org.eclipse.vorto.repository.core.ModelAlreadyExistsException]: {public void org.eclipse.vorto.repository.web.core.PayloadMappingController.modelExists(org.eclipse.vorto.repository.core.ModelAlreadyExistsException), public void org.eclipse.vorto.repository.web.AbstractRepositoryController.ModelExists(org.eclipse.vorto.repository.core.ModelAlreadyExistsException)}
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:189) ~[spring-beans-4.3.17.RELEASE.jar!/:4.3.17.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:588) ~[spring-beans-4.3.17.RELEASE.jar!/:4.3.17.RELEASE]
	... 26 common frames omitted
Caused by: java.lang.IllegalStateException: Ambiguous @ExceptionHandler method mapped for [class org.eclipse.vorto.repository.core.ModelAlreadyExistsException]: {public void org.eclipse.vorto.repository.web.core.PayloadMappingController.modelExists(org.eclipse.vorto.repository.core.ModelAlreadyExistsException), public void org.eclipse.vorto.repository.web.AbstractRepositoryController.ModelExists(org.eclipse.vorto.repository.core.ModelAlreadyExistsException)}
	at org.springframework.web.method.annotation.ExceptionHandlerMethodResolver.addExceptionMapping(ExceptionHandlerMethodResolver.java:110) ~[spring-web-4.3.17.RELEASE.jar!/:4.3.17.RELEASE]
	at org.springframework.web.method.annotation.ExceptionHandlerMethodResolver.<init>(ExceptionHandlerMethodResolver.java:75) ~[spring-web-4.3.17.RELEASE.jar!/:4.3.17.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver.initExceptionHandlerAdviceCache(ExceptionHandlerExceptionResolver.java:270) ~[spring-webmvc-4.3.17.RELEASE.jar!/:4.3.17.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver.afterPropertiesSet(ExceptionHandlerExceptionResolver.java:246) ~[spring-webmvc-4.3.17.RELEASE.jar!/:4.3.17.RELEASE]
	at org.springframework.web.servlet.config.annotation.WebMvcConfigurationSupport.addDefaultHandlerExceptionResolvers(WebMvcConfigurationSupport.java:884) ~[spring-webmvc-4.3.17.RELEASE.jar!/:4.3.17.RELEASE]
	at org.springframework.boot.autoconfigure.web.WebMvcAutoConfiguration$EnableWebMvcConfiguration.configureHandlerExceptionResolvers(WebMvcAutoConfiguration.java:449) ~[spring-boot-autoconfigure-1.5.13.RELEASE.jar!/:1.5.13.RELEASE]
	at org.springframework.web.servlet.config.annotation.WebMvcConfigurationSupport.handlerExceptionResolver(WebMvcConfigurationSupport.java:828) ~[spring-webmvc-4.3.17.RELEASE.jar!/:4.3.17.RELEASE]
	at org.springframework.boot.autoconfigure.web.WebMvcAutoConfiguration$EnableWebMvcConfiguration$$EnhancerBySpringCGLIB$$8d028d29.CGLIB$handlerExceptionResolver$27(<generated>) ~[spring-boot-autoconfigure-1.5.13.RELEASE.jar!/:1.5.13.RELEASE]
	at org.springframework.boot.autoconfigure.web.WebMvcAutoConfiguration$EnableWebMvcConfiguration$$EnhancerBySpringCGLIB$$8d028d29$$FastClassBySpringCGLIB$$b312036.invoke(<generated>) ~[spring-boot-autoconfigure-1.5.13.RELEASE.jar!/:1.5.13.RELEASE]
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228) ~[spring-core-4.3.17.RELEASE.jar!/:4.3.17.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:358) ~[spring-context-4.3.17.RELEASE.jar!/:4.3.17.RELEASE]
	at org.springframework.boot.autoconfigure.web.WebMvcAutoConfiguration$EnableWebMvcConfiguration$$EnhancerBySpringCGLIB$$8d028d29.handlerExceptionResolver(<generated>) ~[spring-boot-autoconfigure-1.5.13.RELEASE.jar!/:1.5.13.RELEASE]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_111]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_111]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_111]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_111]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162) ~[spring-beans-4.3.17.RELEASE.jar!/:4.3.17.RELEASE]
	... 27 common frames omitted
```

**Comment by aedelmann** [comment]
Hi @vlvanchin 
I fixed this in the current Pull Request

**Comment by vlvanchin** [comment]
Dear @aedelmann 
The issue is still there, the last commit "e74a33f" does not fix this.

It looks that the "org.eclipse.vorto.repository.core.ModelAlreadyExistsException" is defined in org.eclipse.vorto.repository.web.core.PayloadMappingController.modelExists(org.eclipse.vorto.repository.core.ModelAlreadyExistsException) and org.eclipse.vorto.repository.web.AbstractRepositoryController.ModelExists(org.eclipse.vorto.repository.core.ModelAlreadyExistsException) classes.
