### ISSUE TITLE
Code generators ignoring `multiple` keyword

### ISSUE THREAD

**Issue by gitolicious** [eclipse/vorto#2004]
When generating code for a very simple functionblock including the `multiple` keyword, the resulting code does not include an array but an object.

**Steps to reproduce:**
* Create a new function block at https://vorto.eclipse.org/
```
vortolang 1.0
namespace vorto.private.myfirstnamespace
version 1.0.0
displayname "MyFirstFunctionBlock"
description "Functionblock for MyFirstFunctionBlock"

functionblock MyFirstFunctionBlock {
  status {
    multiple values as double
  }
}
```
* Use the schema generators.

**Expected result:**
According to [the Vortolang specification](https://github.com/eclipse/vorto/blob/development/docs/vortolang-1.0.md#model-property)

multiple | optional | Indicates if the property is an array type
-- | -- | --

I am expecting an attribute `values` of type array to be created.

**Actual result:**
The `multiple` keyword is ignored and an object of type `number` instead of an array is generated.

JSON Schema:
```
"values": {
  "type": "number"
}
```
Ditto:
```
"values": {
  "type": "number"
}
```
Bosch IoT Suite - Digital Twin API:
```
values:
  type: number
````
Bosch IoT Suite - Connect device with Java:
```
private double values;
```

**Comment by aedelmann** [comment]
fixed.

**Comment by w4tsn** [comment]
I'm still having this issue.

I tested the ditto schema generator on a vorto 0.12.4 instance and build the schema generator with the plugin api v0.12.4. The `multiple -> array` branches of the code won't get executed still.

I used this functionblock model:

```json
vortolang 1.0
namespace org.eclipse.vorto
version 1.0.0
displayname "FBTest"
description "Functionblock for FBTest"

functionblock FBTest {
    status {
	    mandatory multiple foos as string
	    optional date as dateTime
	}
}
```

The resulting schema is this

```json
{
	"$schema": "http://json-schema.org/draft-04/schema#",
	"title": "Properties validation of definition <org.eclipse.vorto:FBTest:1.0.0>",
	"type": "object",
	"properties": {
		"status": {
			"type": "object",
			"properties": {
				"foos": {
					"type": "string"
				},
				"date": {
					"type": "string"
				}
			},
			"required": ["foos"]
		}
	},
	"required" : ["status"]
}
```
