### ISSUE TITLE
Descriptions in DSL for operation signature and datatype models

### ISSUE THREAD

**Issue by nagavijays** [eclipse/vorto#87]
Migrated from https://bugs.eclipse.org/bugs/show_bug.cgi?id=471515

**Comment by erlemantos** [comment]
This should be fixed already. We already have descriptions when defining datatypes, functionblocks and information models.

**Comment by aedelmann** [comment]
Desriptions for datatypes are implemented but operation signature is still missing, right? In this case I will split this task into 2 issues and resolve the description for datatypes part.
